!!python/object/new:attr_dict.AttrDict
dictitems:
  discount: 0.985
  
  eval_episodes: 30
  init_logstd: -1
  init_mean_factor: 0.05
  kl_cutoff_coef: 1000
  kl_cutoff_factor: 2
  kl_init_penalty: 1
  kl_target: 0.01
  logdir: ./logdir/20180614T204603-pybullet_minitaur_rand
  max_length: 1000
  network: !!python/name:networks.ForwardGaussianPolicy ''
  num_agents: 30
  policy_layers: !!python/tuple
  - 200
  - 100
  policy_lr: 0.0001
  policy_optimizer: AdamOptimizer
  
  steps: 30000000.0
  update_epochs_policy: 50
  update_epochs_value: 50
  update_every: 25
  use_gpu: true
  value_layers: !!python/tuple
  - 200
  - 100
  value_lr: 0.0003
  value_optimizer: AdamOptimizer
  weight_summaries:
    all: .*
    policy: .*/policy/.*
    value: .*/value/.*
state:
  _mutable: false
